services:
  - type: web
    name: pdf-saas-app
    env: node
    plan: free
    buildCommand: npm install && npm run build && pip install --target=./backend/python_libs -r requirements.txt
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
